name = "photo-upload"
main = "index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "family-reunion-photos"

[env.production]
routes = [{ pattern = "photo-upload.klsll.com/*", zone_name = "klsll.com" }]

[[env.production.r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "family-reunion-photos"
